js/news.js, setup.php
I think this might make the plugin to malfunction.
At least it breaks Formcreator's service catalog due to the following error
```javascript
$(document).ready(function() {
pluginNewsCloseAlerts();
pluginNewsToggleAlerts();
})
```
and in the file js/news.js there is (again) a $(document).ready() usage.
=> document.ready() used in the main page and the JS script

inc/alert.class.php
```
2017-11-15 14:30:31 [1106@bwgpidev]
*** PHP Notice(8): Undefined index: entities_id
Backtrace :
plugins/news/inc/alert.class.php:498
inc/plugin.class.php:1271                          PluginNewsAlert::preItemForm()
inc/ticket.class.php:3904                          Plugin::doHook()
inc/tickettemplate.class.php:561                   Ticket->showFormHelpdesk()
inc/tickettemplate.class.php:333                   TicketTemplate::showHelpdeskPreview()
inc/commonglpi.class.php:482                       TicketTemplate::displayTabContentForItem()
ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()
```
=> prevent notice

inc/alert.class.php, js/news.js
Hello,
Actually we can't hide alerts with plugin news, because of the declaration of variable ajax_baseurl in document ready function.
With this PR it's solved !
=> Refactoring ajax_base url declaration, because alert hiding doesn't work

inc/alert_target.class.php
Following #67
Allow to delete an alert target if you are allowed to edit an alert.
Internal ref : 16000
=> Delete alert_target rights

inc/alert.class.php
If alert name contains a quote, value is not displayed correctly in alert form.
=> Fix name field input when values contains quotes

setup.php
Alert does not show on the tickets page for the helpdesk in GLPI 9.4.
The pre_item_form hook was ignored because the `Plugin::isPluginLoaded($plug)` check failed as $plug was 'alert' while the loaded plugin name was 'news'.
=> Fix pre_item_form hook

hook.php
Fixes following notice.
```
*** PHP Notice (8): Trying to access array offset on value of type null in /var/www/glpi/plugins/news/hook.php at line 30
Backtrace :
inc/plugin.class.php:623                           plugin_news_install()
front/plugin.form.php:47                           Plugin->install()
```
=> Fix notice on plugin install

css/styles.css, inc/alert.class.php
Before;
After:
I don't really like the lack of contrast but it is consistent with the rest of the dark mode.
=> Dark mode compatibility

inc/alert.class.php
This fix prevent this kind of SQL error to be triggered when $_SESSION['glpiactiveprofile']['id'] is not set (don't ask me how it's possible).
```
inc/dbmysql.class.php line 306
*** MySQL query error:
SQL: SELECT DISTINCT `glpi_plugin_news_alerts`.`id`, `glpi_plugin_news_alerts`.*
FROM `glpi_plugin_news_alerts`
LEFT JOIN `glpi_plugin_news_alerts_users`
ON `glpi_plugin_news_alerts_users`.`plugin_news_alerts_id` = `glpi_plugin_news_alerts`.`id`
AND `glpi_plugin_news_alerts_users`.`users_id` = 2894
AND `glpi_plugin_news_alerts_users`.`state` = 1
INNER JOIN `glpi_plugin_news_alerts_targets`
ON `glpi_plugin_news_alerts_targets`.`plugin_news_alerts_id` = `glpi_plugin_news_alerts`.`id`
AND (
`glpi_plugin_news_alerts_targets`.`itemtype` = 'Profile'
AND ( …
```
=> fix: prevent SQL error when glpiactiveprofile is null

hook.php, inc/alert.class.php
Alerts closed by the user are always displayed (as hidden) even if the option "show on page helpdesk" is set to "no".
This Pr fix this
Internal 21399
=> Fix(display): do not display hidden helpdesk alert

css/styles.css
Hide alert container when it doesn't contain anything to avoid it wasting space with its padding and margin.
=> Hide empty container

inc/alert.class.php
Since #105 , following issue appears on alerts list.
```
PHP Warning: Undefined array key "all_items" in \glpi\plugins\news\inc\alert_target.class.php on line 73
```
=> Fix display of 'All profiles' in alerts list

inc/alert.class.php
Need `form-control` class on text inputs and text areas. Otherwise, legacy CSS is used and dark themes are no properly supported with them (dark text on dark background).
=> Fix text color in dark themes

inc/alert.class.php
Alert content can be richtext and nested `p` tags are not allowed. It pushes the content out of the wrapper `p` element which breaks the expand/collapse. Before the GLPI 10 compatibility changes, the content wrapper was a `div`.
Fixes glpi-project/glpi#11836
=> Fix expand and collapse of alert messages

inc/alert.class.php
This field is supposed to be using rich text: 
After fix:
It seems like `Html::initEditorSystem` expected a textarea name in the past (the field is displayed correctly in GLPI 9.5) but now it expect an ID.
=> Alert form: fix missing richtext editor

templates/alert_form.html.twig
Small mistake after replacing some `:select` by `select` in #121's review.
=> Fix invalid selector

inc/alert.class.php
Needed to also edit `prepareInputForAdd` as it would trigger the missing name check when trying to run an unrelated update through massive actions.
=> Enable "Active" search option for massive actions

CHANGELOG.md, inc/alert.class.php, templates/alert_form.html.twig, templates/display_alert.html.twig
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !32277
Correction of alert text wrapping to prevent it from going outside the div of its alert
**Before :** 
**After :**
=> Fix of alert text wrapping

inc/alert.class.php
If a target is configured for an Alert. Ex: Alerts 1 :
If we log in with a profile that is not one of the targets, we still see the alert.
Related ticket : !32722
=> Fix SQL query that finds alerts to display to the user

.php-cs-fixer.php, ajax/display_alerts.php, ajax/hide_alert.php, ajax/targets.php, composer.json, composer.lock, front/alert.form.php, front/alert.php, front/external.php, front/hidden_alerts.php, hook.php, inc/alert.class.php, inc/alert_target.class.php, inc/alert_user.class.php, inc/profile.class.php, setup.php
=> Feat: php-cs-fixer
